# Generated by Django 3.0.6 on 2020-06-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_form_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
    ]
